apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:7cc5c17b676dc8b2d580b6ed8ee90cb031a7321680b47852a277b3cdd94d45a7
  name: quay.io/jpercivaldbxcorp/vote-api
  newName: quay.io/jpercivaldbxcorp/vote-api
